### ISSUE TITLE
Cliking 'take a photo...' menu stop app instantly when  minSdkVersion >= 24 

### ISSUE THREAD

**Issue by justinFather** [andreipfeiffer/react-native-webview-android-file-upload#1]
Hi,

I tried minSdkVersion = 23 then it's working correctly. But minSdkVersion >= 24, the app stops instantly.

So I debugged your code in Android Studio though I am not a java engineer.

I got the message on debugging mode in Android Studio as below

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.mydomian.mobile, PID: 17097
                  android.os.FileUriExposedException: file:///storage/emulated/0/Download/image-1914299633.jpg exposed beyond app through ClipData.Item.getUri()
                      at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
                      at android.net.Uri.checkFileUriExposed(Uri.java:2346)
                      at android.content.ClipData.prepareToLeaveProcess(ClipData.java:845)
                      at android.content.Intent.prepareToLeaveProcess(Intent.java:9016)
                      at android.content.Intent.prepareToLeaveProcess(Intent.java:9001)
                      at android.app.Instrumentation.execStartActivity(Instrumentation.java:1519)
                      at android.app.Activity.startActivityForResult(Activity.java:4318)
                      at android.app.Activity.startActivityForResult(Activity.java:4276)
                      at com.rncustomwebview.CustomWebViewModule.startCamera(CustomWebViewModule.java:148)
                      at com.rncustomwebview.CustomWebViewModule.access$000(CustomWebViewModule.java:26)
                      at com.rncustomwebview.CustomWebViewModule$2.onClick(CustomWebViewModule.java:110)
                      at com.android.internal.app.AlertController$AlertParams$4.onItemClick(AlertController.java:1153)
                      at android.widget.AdapterView.performItemClick(AdapterView.java:310)
                      at android.widget.AbsListView.performItemClick(AbsListView.java:1200)
                      at android.widget.AbsListView$PerformClick.run(AbsListView.java:3179)
                      at android.widget.AbsListView$3.run(AbsListView.java:4233)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6349)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
```

This was all I could as javascript engineer.

Thank you

**Comment by viv3kk** [comment]
Same issue... app closed on **take a photo** option. using rn-0.56 and android SDK 26

**Comment by akamittal** [comment]
@justinFather @viv3kk @andreipfeiffer 
I think the issue is related with android camera permission. For now I turned off "**take a photo**" option in my application.

If you wish you can also turn off in your project. Here are the steps -
1. Open **CustomWebViewModule.java** (node_modules\react-native-webview-android-file-upload\android\src\main\java\com\rncustomwebview\CustomWebViewModule.java)

2. Update this function as shown below -
```
private CharSequence[] getDialogItems(String[] types) {
        List<String> listItems = new ArrayList<String>();

        if (acceptsImages(types)) {
            //listItems.add(TAKE_PHOTO); //We have commented this out so that it won't get listed in listitems.
        }
        if (acceptsVideo(types)) {
            listItems.add(TAKE_VIDEO);
        }

        listItems.add(CHOOSE_FILE);
        listItems.add(CANCEL);

        return listItems.toArray(new CharSequence[listItems.size()]);
  }
```
This way users won't have option to use camera directly.

**Comment by andreipfeiffer** [comment]
@justinFather I'm sorry I didn't reply to you sooner, but I didn't get any notification of this issue.

@justinFather @viv3kk 
Can you tell me what version of this module do you use?
Version `1.2.0` supports sdk 26. I am currently using it with RN 0.54 + targetSdkVersion 26.

**Comment by andreipfeiffer** [comment]
I've just tested `v1.2.0` locally on a brand new rn-0.56 project and the plugin works as expected.

Tested on:
* emulator sdk 23
* emulator sdk 26
* HTC M10 with Android 8.0 (sdk 26)

**Comment by andreipfeiffer** [comment]
@justinFather you could leave `minSdkVersion` to the default one, which is `16` in RN.
I don't believe you get any benefit from incrementing it.

Google Play requires you to upgrade only the `targetSdkVersion` to `26`:
https://developer.android.com/distribute/best-practices/develop/target-sdk

**Comment by viv3kk** [comment]
> I've just tested v1.2.0 locally on a brand new rn-0.56 project and the plugin works as expected.

Tested on:

emulator sdk 23
emulator sdk 26
HTC M10 with Android 8.0 (sdk 26)

**Comment by andreipfeiffer** [comment]
@viv3kk please keep in mind that in order to support sdk 26, additional setup is required, as documented in the README, mostly in regard to how the files are stored and how the permissions work.

**Comment by viv3kk** [comment]
> Mine is same too.. v1.2.0 and rn-0.56. I hv tested the same on OPO(Bacon)(8.1) and moto 3 turbo(7.1). As soon as i use camera option, app crashed

.

ext {
    buildToolsVersion = "26.0.3"
    minSdkVersion = 16
    compileSdkVersion = 26
    targetSdkVersion = 26
    supportLibVersion = "26.1.0"
}

**Comment by viv3kk** [comment]
Also I am unable to upload multiple photos when using the file upload.

**Comment by andreipfeiffer** [comment]
@viv3kk did you setup the File Provider, as described in the README?

In regard to `multiple files upload`, you're right, it won't work, because it's not handled anywhere.
Would be a nice addition, though.

**Comment by viv3kk** [comment]
> @viv3kk did you setup the File Provider, as described in the README?
Just tried that but it failed again

**Comment by andreipfeiffer** [comment]
@viv3kk can you paste the error output from Android Studio?

**Comment by viv3kk** [comment]
I am trying to rebuild the app. Please wait for 10 min.

**Comment by viv3kk** [comment]
Holyshit... it works....thanks thanls thanks

**Comment by viv3kk** [comment]
Please provide a way to upload multiple photos

**Comment by andreipfeiffer** [comment]
I'll look into it when I find some free time. I'm not an Android developer, so it's not that easy for me neither :)

**Comment by viv3kk** [comment]
> I'll look into it when I find some free time. I'm not an Android developer, so it's not that easy for me neither :)
Thanks looking forward to it.

**Comment by andreipfeiffer** [comment]
@justinFather can I still help you with your issue? I know it's been a long time since you've posted it.

**Comment by geoseong** [comment]
+1
I'm so frustrated having this app crash..

I'm not a Android Dev, but I can see Java code, I modified a little `private void startCamera` method at `CustomWebViewModule.java`.

The reason that app crash was due to mismatch between `Manifest.permission` and `PackageManager.PERMISSION_GRANTED`.

so I append `ActivityCompat.requestPermissions()` method.. but for some reasons Overriding `onRequestPermissionsResult()` method is not working so that I couldn't call `getCurrentActivity().startActivityForResult(intent, REQUEST_CAMERA);` as callback function of javascript.
so I append `if` syntax temporarily and call `getCurrentActivity().startActivityForResult(intent, REQUEST_CAMERA);`

plz let me know if you guys fix the legal problem...

```
private void startCamera(String intentType, String prefix, String suffix) {

        // bring up a camera picker intent
        // we need to pass a filename for the file to be saved to
        Intent intent = new Intent(intentType);

        // Create the File where the photo should go
        try {
            String packageName = getReactApplicationContext().getPackageName();
            File capturedFile = createCapturedFile(prefix, suffix);

            outputFileUri = FileProvider.getUriForFile(getReactApplicationContext(), packageName+".fileprovider", capturedFile);
            intent.putExtra(MediaStore.EXTRA_OUTPUT, outputFileUri);

            int manifest_permission = ContextCompat.checkSelfPermission(getCurrentActivity(), Manifest.permission.CAMERA);
            Log.i("[geoseong]", "[geoseong]manifest permission=" + manifest_permission);

            int package_permission = PackageManager.PERMISSION_GRANTED;
            Log.i("[geoseong]", "[geoseong]package permission=" + package_permission);

            // GET CAMERA PERMISSION(actually 'Manifest' got Camera permission but 'PackageManager' didn't get Camera permission so this is the code how to get CAMERA permission)
            ActivityCompat.requestPermissions(getCurrentActivity(), new String[]{Manifest.permission.CAMERA}, REQUEST_CAMERA);

            if(manifest_permission == package_permission){
                getCurrentActivity().startActivityForResult(intent, REQUEST_CAMERA);
            }else{
                startCamera(intentType, prefix, suffix);
            }

        } catch (IOException ex) {
            Log.e("CREATE FILE", "Error occurred while creating the File", ex);
        }
    }
```

**Comment by andreipfeiffer** [comment]
@geoseong what phone do you test on?
Also, can you please paste your `AndroidManifest.xml`?

**Comment by andreipfeiffer** [comment]
@geoseong 
- also, do you use the example app?
- or did you included this in your own app?

I can implement the "new" Permission model, to check at runtime and request if not granted.
I just need a consistent device/emulator to develop/test on.
I'll try create emulators with sdk 24 & 25.
But I don't know exactly when I'll have some free time for this.

**Comment by andreipfeiffer** [comment]
@geoseong can you please tell me the Android version / SDK level of your phone?

`ReferenceError: Can't find variable: process` looks like a RN internal error, their repo is full of such issues.

I'm downloading now emulators for all SDK levels greater than 23, to try to reproduce the issue.

**Comment by geoseong** [comment]
@andreipfeiffer 
- Device
  - `Xiaomi Mi A1` : `Android 8.0.0 / 26`
  -  `Galaxy J5(2016)` : `Android 6.0.1 / 23`

**Comment by andreipfeiffer** [comment]
@geoseong is your project on a public repo? I'm curious if it's working on my device. Every device I've tested on (emulator & real) it works, so I have no other idea how to reproduce this, unless I try your code.

**Comment by geoseong** [comment]
@andreipfeiffer I want to know what is the reason...

I uploaded my sample app to public repo.

 [https://github.com/geoseong/rn-temp-webview](https://github.com/geoseong/rn-temp-webview)

Thanks for your help~!

**Comment by andreipfeiffer** [comment]
@geoseong I had to add `google()` repository in your `android/build.gradle` file before `jcenter()` just to be able to compile your project (this is required to fetch the support libraries, afaik):
```
buildscript {
    repositories {
        google() // <=== added this
        jcenter()
    }
    ...
}

allprojects {
    repositories {
        mavenLocal()
        google() // <=== added this
        jcenter()
        ...
    }
}
```

Then, I've removed from `AndroidManifest.xml`:
```
<uses-permission android:name="android.permission.CAMERA"/>
```

And it works.

Before I removed it, indeed, my app crashed.
Hope it works for you too.

**Comment by geoseong** [comment]
@andreipfeiffer OMG.. so simple solution.. removing CAMERA permission in `AndroidManifest.xml`.

it works!

Thank you very much for your support!! big thumbs up lol
