### ISSUE TITLE
Choose an existing file works great, take a photo crashes the app

### ISSUE THREAD

**Issue by krokhale** [andreipfeiffer/react-native-webview-android-file-upload#10]
Followed the instructions, double checked everything, seems to work fine until i try to take a pic from the cam, how do i disable take a pic from cam option since it's not working? ideas?

**Comment by andreipfeiffer** [comment]
What is the error message from Android Studio?
Can you share your repo?
For sure it's a problem with the permissions.

**Comment by krokhale** [comment]
Yeah i think it's permissions too, can i share the android folder? Or maybe just the AndroidManifest.xml?

**Comment by andreipfeiffer** [comment]
The entire Android folder would be more convenient.

**Comment by krokhale** [comment]
Here you go: https://github.com/krokhale/android-webview

**Comment by andreipfeiffer** [comment]
The camera permissions look weird to me, can you try removing these?

```
<uses-feature android:name="android.hardware.camera" android:required="true" />
<uses-feature android:name="android.hardware.camera.autofocus" android:required="false" />
<uses-feature android:name="android.hardware.microphone" android:required="true" />
```

**Comment by andreipfeiffer** [comment]
You should not ask for any explicit permissions for the camera / microphone.
The `FileProvider` should take care of these, it gets temporary permissions to capture content.

**Comment by krokhale** [comment]
Yeah unfortunately, the app uses video calls and we need the audio/video/cam portion of those permissions for other modules.

Is it possible to hide take a picture option? I can live with folks choosing a file from gallery for now.

**Comment by andreipfeiffer** [comment]
Yes, you can hide it, but it is not configurable at client level.

1. you could try a hack, to add `accepts="nothing"` on your `input` element. This might disable Photo & Video capture.

2. If not, you have to comment out from https://github.com/andreipfeiffer/react-native-webview-android-file-upload/blob/master/android/src/main/java/com/rncustomwebview/CustomWebViewModule.java#L204:

```diff
        if (acceptsImages(types)) {
-            listItems.add(TAKE_PHOTO);
+            //listItems.add(TAKE_PHOTO);
        }
        if (acceptsVideo(types)) {
-            listItems.add(TAKE_VIDEO);
+            //listItems.add(TAKE_VIDEO);
        }
```

**Comment by krokhale** [comment]
This solved it for me:

Just added an explicit permission grant from the user for camera before clicking the select file button. Bam!

https://facebook.github.io/react-native/docs/permissionsandroid
