### ISSUE TITLE
 bundling failed: Error: Unable to resolve module `react-native-webview-android-file-upload` from `D:\code\xiancai\App\screens\webView.js`: Module `react-native-webview-android-file-upload` does not exist in the Haste module map

### ISSUE THREAD

**Issue by zwrqq2009** [andreipfeiffer/react-native-webview-android-file-upload#13]
bundling failed: Error: Unable to resolve module `react-native-webview-android-file-upload` from `D:\code\xiancai\App\screens\webView.js`: Module `react-native-webview-android-file-upload` does not exist in the Haste module map

import CustomWebView from "react-native-webview-android-file-upload";

<CustomWebView
					source={{ uri: "http://xiancai888.com/" }}
					startInLoadingState={true}
				/>

Big boss to help solve!

**Comment by zwrqq2009** [comment]
and yarn Can't install

**Comment by andreipfeiffer** [comment]
Sorry for the late reply. It seems that you don't have the npm package installed.
You could try:
`npm i https://github.com/andreipfeiffer/react-native-webview-android-file-upload.git`

**Comment by zwrqq2009** [comment]
@andreipfeiffer I solved  problem by copying index.js in your directory into my project and importing, just like import CustomWebView from './custom'.
But I met a new problem, I do. / gradlew installRelease in: when the app: bundleReleaseJsAndAssets't respond at this stage!

**Comment by zwrqq2009** [comment]
@andreipfeiffer Can you help me out? Thanks !

**Comment by andreipfeiffer** [comment]
@zwrqq2009 can you please provide more context and details to your problem? I don't understand:
* what are you trying to do?
* what is the problem?

**Comment by zwrqq2009** [comment]
Could I  have your email address so I can provide screenshots with more details? Thanks a lot!

**Comment by andreipfeiffer** [comment]
You can upload them here, also.
Or you can send them to `andrei@upsidedown.ro`
