### ISSUE TITLE
Unable to use rn-fetch-blob : file_provider_paths error

### ISSUE THREAD

**Issue by viv3kk** [andreipfeiffer/react-native-webview-android-file-upload#20]
/home/company/react_projects/myApp_production_v1.1/android/app/src/main/AndroidManifest.xml:69:13-64 Error:
        Attribute provider#android.support.v4.content.FileProvider@authorities value=(com.myApp.fileprovider) from AndroidManifest.xml:69:13-64
        is also present at [:rn-fetch-blob] AndroidManifest.xml:38:13-60 value=(com.myApp.provider).
        Suggestion: add 'tools:replace="android:authorities"' to <provider> element at AndroidManifest.xml:67:9-75:20 to override.
/home/justdial/react_projects/myApp_production_v1.1/android/app/src/main/AndroidManifest.xml:74:17-60 Error:
        Attribute meta-data#android.support.FILE_PROVIDER_PATHS@resource value=(@xml/file_provider_paths) from AndroidManifest.xml:74:17-60
        is also present at [:rn-fetch-blob] AndroidManifest.xml:43:17-55 value=(@xml/provider_paths).
        Suggestion: add 'tools:replace="android:resource"' to <meta-data> element at AndroidManifest.xml:72:13-74:63 to override.

**Comment by viv3kk** [comment]
kindly help me to resolve this.

**Comment by andreipfeiffer** [comment]
@viv3kk try this solution here: https://github.com/jkwiecien/EasyImage/issues/108
It describes your exact problem, afais.

**Comment by viv3kk** [comment]
Thanks a lote...it works..cheers...
