### ISSUE TITLE
problem build apk 

### ISSUE THREAD

**Issue by hellohaidev** [andreipfeiffer/react-native-webview-android-file-upload#22]
i have problem when build my app 
 Task :react-native-webview-android-file-upload:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-webview-android-file-upload:verifyReleaseResources'.

**Comment by hellohaidev** [comment]
@andreipfeiffer can help
 Task :react-native-webview-android-file-upload:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-webview-android-file-upload:verifyReleaseResources'.

**Comment by andreipfeiffer** [comment]
@hellohaidev please use the `react-native-webview` package.

Also, please provide the error message here and let's continue the discussion here:
https://github.com/react-native-community/react-native-webview/issues/379

This repo is deprecated and obsolete.
Thank you.
