### ISSUE TITLE
Unable to get this running

### ISSUE THREAD

**Issue by nconroy** [andreipfeiffer/react-native-webview-android-file-upload#9]
I have installed and linked the component but get this error when trying to build:
```

react-native-webview-android-file-upload/android/build.gradle' line: 16

* What went wrong:
A problem occurred evaluating project ':react-native-webview-android-file-upload'.
> Could not find method implementation() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

I went through the manual link steps and all the config seems correct.
Version
react-native-cli: 2.0.1
react-native: 0.55.2

**Comment by andreipfeiffer** [comment]
Hey @nconroy 
It looks like you are using an older Gradle version.
Change all your `implementation` with `compile` and it should work.

**Comment by levi-beers** [comment]
Hi @andreipfeiffer -- I too had the same issue, it took me a few minutes to figure out there was a build.gradle file with implementation enabled in the react native package, not just in the main/app build.gradle's. That said, I have it running perfectly on RN 0.56. This is the ONLY solution to file uploading on Android that I've found to work. You are a genius.

**Comment by andreipfeiffer** [comment]
Hey @levi-beers I'm really glad you find this useful, it means that this package reached its purpose (:

I have added a comment in the README in regard to `implementation` vs. `compile`.
If you think it's not clear enough, or additional explanations are needed, please let me know.
Best wishes.
